[package]
name = "rusty-money"
version = "0.3.4"
authors = ["Varun Srinivasan <varunsrin@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/varunsrin/rusty_money"
documentation = "https://docs.rs/rusty-money"
description = """
Money type for Rust.
"""
keywords = ["money", "currency", "iso-4217", "exchange"]
categories = ["data-structures", "rust-patterns"]


[dependencies]
rust_decimal = "1.4.1"
rust_decimal_macros = "1.4.1"
lazy_static = "1.4.0"
