[package]
name = "rusty-money"
version = "0.2.0"
authors = ["Varun Srinivasan <varunsrin@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/varunsrin/rusty_money"
documentation = "https://docs.rs/rusty-money"
description = """
Handle currencies in Rust.
"""
keywords = ["money", "currency", "iso-4217", "exchange"]
categories = ["data-structures", "rust-patterns"]


[dependencies]
rust_decimal = "1.0.3"
rust_decimal_macros = "1.0.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
